server:
  port: 8083

spring:
  datasource:
    url: '{cipher}AQBal7Dlq6C5+q5kpctmzWUCj79jqlaqJFsxJVotX4hemrIPB/VXgj3qCrNNsbuiz1nJQrm7IwLDa5BgqR/QS29Oew/rsiQmGAbunnhuMse2st2F8TGjzKrffRkzMjVocbSCuDNcpr4bn1yVlTutwQl/R0LYYzIX7XzGqEDIGQeOq8YDZl2t8tG2I+9SdlYqzRzp7oPz3BgUaaKyzxZVW2h/FEJCxzemQ/b3TN37WM95WJPQAu5U4Ac5AD/RRDqK99kbkuUWshHWQ3ITGUYB3AkN2sP2in8AdT2lfI0R/SmhahW9+Xqm5FSdj8xuqGMswnYd0QGBD9KD7vjJGV1/0lU+uPUAXXDGOhcD8jfKWr8wEnZ0ffWdqQJ2zI98se3q6LI='
  jpa:
    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
            indexBase: lucene/indexes
lucene:
  queryParser:
    leadingWildcard: true

notification:
  ribbon:
    listOfServers: http://localhost:8003
