server:
  port: 8082

spring:
  datasource:
    url: '{cipher}AQAbxyRogpZ5xV5tdXMbJ0AxRi2VnVDFEcek48DhrOYH/nmcNgx44tWTSRP5PqMb3TtpxVV3WwK7lWQgFu3wBItGY8CURy6bZsEQ05N9ZlLC3UCEm/mdKqkpNRjSYDJxR3LqHdv2X8XZtjvzY8sE3DnMddz3FMPiUCgwwOUdd93G8/RFWJ/DnTYn+oGq8eDtl6ZS6gsf1jJJKH0TbQx/qu+MJf2TQ4pWmjB5zkcY1NR0M+jdm4s2pdSJrO0WfJDecQ27vc+nnGWx23LzS1TgCKiNt+2sZ44q9mfyJnikIOsz2Fl/rXSS12+OXa4jRg0FRwnciF1XQmEtFalQ49qizPaDBkykqVd3aDBrDi+agvpKWuNx8Y29x39qQsFclvD214tq+yRa0xbBvg+uw3zkar6DrzjiMrcx5Jrg37ctAhpLeb8dRZkM1pAdLy7+SS7vh6Y='

file:
  storage:
    enabled: true
    bucketName: '{cipher}AQCG8+0RR3/N9KZFBxwvLFWGJUbl3bTeEgRji5pD6agnhccV1Ur1d2DjrFfjuFRQowRLbfYrGtiTReJhH/cDFWQ9bdwIX6/9W8QWxpb/WLl+YpfTZ4MiQ/du8fHeinAksBjnsCYQSaZFH3RwAuewWmaX6HMBMCI30qQELY8+YKwIvbDuN4XSDgVXWZUFfQs8YdsRrU4s4yYc2VmsA643uTX1hDSlItZkS3I9MjQNz0uQudYAJ1Dvu53tYaM3Bupe8rd19RBVLI1DwRpN3Klq8XaRREt+FyYiyPzGHVTFTfg5mvsAWO9MZmT/No176Ple1ZKTQvEXN5k3d/wLCxBqyBEDOkDRkzs7FcbmlSo1NhKn9WAxB/pRkuxUUed2QzFHemzGQYLamVbkMw84X1+kW6XZ'
