server:
  port: 8082

spring:
  datasource:
    url: '{cipher}AQBDZOFBjclJ4Heo3dCDDmYyUUixc/vUDqtnSfH4Y7zsT8jPOcIa+mawDxj0rh8j1rk1AJ9EflyW71hrajONk1h6KDrCncBul2ZYV1kRwAHydY5L8E4SaDfqGL5ukCNqB3bpk4X++oG5+HKyxTIoHIRn2AW6VkVg/cpCLLbTQxMpwwl7ebUtbP+2qOvDWsBOppYXc1bggOnyT3z+tUg4Uy8OhWevKMFTQK4lUgVtPF2bvCjeQdzEwfN7RVFEzEZPFe0peFNcsZoLBBN5l43v0ic1ay42UoL+r2VESLKE3/czrID0XcUbRekAHtsrYVduBBlaqU7h+51zVrweVpazgTRbwAUm+rudGpHAs0QBSMpwt+UUuWtOtE3HwdqASN1WMcYfHGTeOkbD7rqspkHKm7TO3y+DECJ2USmUH4idpYY7NY2+BWlwx/RP7NcT+gQ8qfY='

file:
  storage:
    enabled: true
    bucketName: '{cipher}AQCG8+0RR3/N9KZFBxwvLFWGJUbl3bTeEgRji5pD6agnhccV1Ur1d2DjrFfjuFRQowRLbfYrGtiTReJhH/cDFWQ9bdwIX6/9W8QWxpb/WLl+YpfTZ4MiQ/du8fHeinAksBjnsCYQSaZFH3RwAuewWmaX6HMBMCI30qQELY8+YKwIvbDuN4XSDgVXWZUFfQs8YdsRrU4s4yYc2VmsA643uTX1hDSlItZkS3I9MjQNz0uQudYAJ1Dvu53tYaM3Bupe8rd19RBVLI1DwRpN3Klq8XaRREt+FyYiyPzGHVTFTfg5mvsAWO9MZmT/No176Ple1ZKTQvEXN5k3d/wLCxBqyBEDOkDRkzs7FcbmlSo1NhKn9WAxB/pRkuxUUed2QzFHemzGQYLamVbkMw84X1+kW6XZ'
