server:
  port: 8085

spring:
  datasource:
    url: '{cipher}AQAn09W5Oe6H6i8yxlr1UCpwGcrE/cTJgb5qR5cgsgmplUiXomCEkgl1kmlW+fbPNNNMcPhSJXt/DRs1F2IjcShKEn8d/ATjActSBjmVFBbcLfjfgNFNiJFtjSWJ0/G6K6FIwYQYLvhBIbqx4j0E9/39EJerf1K6CZUXPitMMEdr/vGX0qET5dozoSRPfgtT2s1FWn45QZJkzthf+sy13YsThtlMujsg3WIApHQLtuQX3J4GF99muAOmusAFYnQwCkZxWNNYNlJSFNrCymzb2XAh93doB+PuBnoYaHrfoqhjyZu1/9s9/lh3GeKma4eN8wvp8KUfZ9Z4X7RtnYzJj1vMTIYccOSloO5N472q2oGbi/ReOV/jwEuCHuzoQGq1ZSLdjKEP8h5WjqUW0Cz03L+5vpJZ2/lTI5y0nkPHWJzjJCsc7iQol9d02EzSK1oQZfs='

bpmn:
  ribbon:
    listOfServers: http://localhost:9999
