server:
  port: 8086

spring:
  datasource:
    url: '{cipher}AQAJlcdcGL+2+P2tTlSa8ADU4yPYvIIjlvGElZiKxZ/9J8LnBbdIYSmUoL/imRc8DcGSRZDw/zwaDqbQKUWANdHuf7DifuQyx6P4Z7WGzFZ2WeRjQ/RFpCBSnOPaCSNfbe0TL6xazMB5ZhjaVp8uHw4668HMyN2o2xTZYGkEidAZ8MFFKeejEhY8hKQfZuycGbr5Cdg53elt6XbNdnT3wHS6DRHlY3h+TS/StWbz1/W9wTB9XoprBBanQgHVV/M1wUyKTqHMuD40Y/XhYpFUkUZWjQXaULwfIKiLAh7h0sx/BOcW+6G5ZpGmXWPJQoMuBfAC0fc9Hgm/R4Z8j2gkp8TESu9oRnLF3SVX6+GfaBqjt/Nttaz0ZFbWHNh7LgUK8PQuk4Sp1EcZuyv5uV95vuWXactWuueMHbUjTyQ84khTMB6kX5kdep+qSE8NL5vx3ek='

bpmn:
  ribbon:
    listOfServers: http://localhost:9999
