server:
  port: 8084

spring:
  datasource:
    url: '{cipher}AQCIXd1JOPNzSwmQaHdG6GImXUOmYtNq9ckVZppWEc/dpWPV50cZZAxzLgjQJBZLykXm4Jwm+TbewB/PgyjS04pMZtDwGhAyVJtfNhPwV6tcPMh6jHjf2Q+NnAenMQZslENPTH8xBiFHv/ivGVP06eVfh4s4BnL9A8AufvkZN88P6NFX4S1B2Gy8X98SnBp57nxWt/ITQE4kyd2sOPQEWmAe7PAMEl5R/OzlHBTCc/AD9IYesFkO6uYCDhb49WWtOx4ffUorWLeNWsylUoH1iLi9qmSlkZjq06ukMHBdifiDO1PS3C6B8RdFQxrAQpwUEJHyrgL8J2gGSOaRvuf2wAViIVO//c4gpwjoo9x4NxOm0NFcj2q6+LGp2cpCmf39+Mvfox/h7HRkUAUQJHkCIQl4C6cM7CePlgX0Vb8kGOVqoMtoGUVqHsxLRUacmFrJvDM='

bpmn:
  ribbon:
    listOfServers: http://localhost:9999
