server:
  port: 8084

spring:
  datasource:
    url: '{cipher}AQAFFHQUgV7N/DTYoyk9M4Ot4KNFAUGgSWSoXmGUdspMsWAqjk4eZJ1FKDG8ZAoLfOFF7T6ScKyPd1lHQmT7nxq6/9CT759928u0N3gilcvZNXpXm2rIeTUmO5oxijcv48ElKGc0DJu03ziQVqSVdh9AdOK8ujc9Y45ID8Z04GzyaKpRll+3SWbMg4SiQKMckUXz/nTfSBpmDz9OXnIfbhCgnR7mf2NaFeuKhfgGpPPLAiX0oxNr07P2yGrni/swaVV5hcahlj8TjsCeOvcDItq3Xju+iL5qwfZs0XADxOCdwZ/mQV3d/0aKg36e8hKjL5rggsRfuIEFNEdTip5FsOCVQydaC5Ry57oX0eG8GroLORx8inWGNEDuzIJzOqdfUDG7C2yDRKKiPL9UM9ESIQK+yVBf8xCrW/tlHNCcVIq0o8chC9DNsnP/2S2oYBt9pLA='

bpmn:
  ribbon:
    listOfServers: http://localhost:9999
